// Generated by gencpp from file uav_msgs/Takeoff.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_TAKEOFF_H
#define UAV_MSGS_MESSAGE_TAKEOFF_H

#include <ros/service_traits.h>


#include <uav_msgs/TakeoffRequest.h>
#include <uav_msgs/TakeoffResponse.h>


namespace uav_msgs
{

struct Takeoff
{

typedef TakeoffRequest Request;
typedef TakeoffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Takeoff
} // namespace uav_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_msgs::Takeoff > {
  static const char* value()
  {
    return "3a122444608b7d9984b24a10fba10ac1";
  }

  static const char* value(const ::uav_msgs::Takeoff&) { return value(); }
};

template<>
struct DataType< ::uav_msgs::Takeoff > {
  static const char* value()
  {
    return "uav_msgs/Takeoff";
  }

  static const char* value(const ::uav_msgs::Takeoff&) { return value(); }
};


// service_traits::MD5Sum< ::uav_msgs::TakeoffRequest> should match
// service_traits::MD5Sum< ::uav_msgs::Takeoff >
template<>
struct MD5Sum< ::uav_msgs::TakeoffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::Takeoff >::value();
  }
  static const char* value(const ::uav_msgs::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::TakeoffRequest> should match
// service_traits::DataType< ::uav_msgs::Takeoff >
template<>
struct DataType< ::uav_msgs::TakeoffRequest>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::Takeoff >::value();
  }
  static const char* value(const ::uav_msgs::TakeoffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_msgs::TakeoffResponse> should match
// service_traits::MD5Sum< ::uav_msgs::Takeoff >
template<>
struct MD5Sum< ::uav_msgs::TakeoffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_msgs::Takeoff >::value();
  }
  static const char* value(const ::uav_msgs::TakeoffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_msgs::TakeoffResponse> should match
// service_traits::DataType< ::uav_msgs::Takeoff >
template<>
struct DataType< ::uav_msgs::TakeoffResponse>
{
  static const char* value()
  {
    return DataType< ::uav_msgs::Takeoff >::value();
  }
  static const char* value(const ::uav_msgs::TakeoffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MSGS_MESSAGE_TAKEOFF_H
