// Generated by gencpp from file uav_msgs/TakeoffRequest.msg
// DO NOT EDIT!


#ifndef UAV_MSGS_MESSAGE_TAKEOFFREQUEST_H
#define UAV_MSGS_MESSAGE_TAKEOFFREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_msgs
{
template <class ContainerAllocator>
struct TakeoffRequest_
{
  typedef TakeoffRequest_<ContainerAllocator> Type;

  TakeoffRequest_()
    : waitOnLastTask(false)  {
    }
  TakeoffRequest_(const ContainerAllocator& _alloc)
    : waitOnLastTask(false)  {
  (void)_alloc;
    }



   typedef uint8_t _waitOnLastTask_type;
  _waitOnLastTask_type waitOnLastTask;





  typedef boost::shared_ptr< ::uav_msgs::TakeoffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_msgs::TakeoffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TakeoffRequest_

typedef ::uav_msgs::TakeoffRequest_<std::allocator<void> > TakeoffRequest;

typedef boost::shared_ptr< ::uav_msgs::TakeoffRequest > TakeoffRequestPtr;
typedef boost::shared_ptr< ::uav_msgs::TakeoffRequest const> TakeoffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_msgs::TakeoffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_msgs::TakeoffRequest_<ContainerAllocator1> & lhs, const ::uav_msgs::TakeoffRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waitOnLastTask == rhs.waitOnLastTask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_msgs::TakeoffRequest_<ContainerAllocator1> & lhs, const ::uav_msgs::TakeoffRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_msgs::TakeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_msgs::TakeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_msgs::TakeoffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79b3eea4e90fd67af16afc9085f08e12";
  }

  static const char* value(const ::uav_msgs::TakeoffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79b3eea4e90fd67aULL;
  static const uint64_t static_value2 = 0xf16afc9085f08e12ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_msgs/TakeoffRequest";
  }

  static const char* value(const ::uav_msgs::TakeoffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool waitOnLastTask \n"
;
  }

  static const char* value(const ::uav_msgs::TakeoffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waitOnLastTask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeoffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_msgs::TakeoffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_msgs::TakeoffRequest_<ContainerAllocator>& v)
  {
    s << indent << "waitOnLastTask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.waitOnLastTask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MSGS_MESSAGE_TAKEOFFREQUEST_H
